version: '2'

services:
  config-service:
    build: config-service
    restart: always
    ports:
    - "8888:8888"

  eureka-service:
    build: eureka-service
    restart: always
    ports:
    - "8761:8761"

  book-service:
    build: book-service
    restart: always
    ports:
    - "8000:8000"

  book-client:
    build: book-client
    restart: always
    ports:
    - "9999:9999"

  zipkin-service:
    build: zipkin-service
    restart: always
    ports:
    - "9411:9411"

  auth-service:
    build: auth-service
    restart: always
    ports:
    - "9191:9191"

  hystrix-dashboard:
    build: hystrix-dashboard
    restart: always
    ports:
    - "8010:8010"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"