version: '2'

services:
  config-service:
    build: config-service
    restart: always
    ports:
     - "8888:8888"

  eureka-service:
    build: eureka-service
    restart: always
    ports:
     - "8761:8761"

  book-service:
    build: book-service
    entrypoint:
     - java
     - -Djava.security.egd=file:/dev/./urandom
     - -Dspring.profiles.active=elk
     - -jar
     - /app.jar
    restart: always
    ports:
     - "8000:8000"

  book-client:
    build: book-client
    entrypoint:
     - java
     - -Djava.security.egd=file:/dev/./urandom
     - -Dspring.profiles.active=elk
     - -jar
     - /app.jar
    restart: always
    ports:
     - "9999:9999"

  auth-service:
    build: auth-service
    entrypoint:
     - java
     - -Djava.security.egd=file:/dev/./urandom
     - -Dspring.profiles.active=elk
     - -jar
     - /app.jar
    restart: always
    ports:
     - "9191:9191"

  zipkin-service:
    build: zipkin-service
    restart: always
    ports:
     - "9411:9411"

  hystrix-dashboard:
    build: hystrix-dashboard
    restart: always
    ports:
     - "8010:8010"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "15672:15672"

  elasticsearch:
   image: elasticsearch:5.0
   ports:
    - 9200:9200
   volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    build: logstash
    command: logstash -f /config-dir/logstash.conf
    links:
     - elasticsearch

  kibana:
    image: kibana:5.0
    ports:
     - 5601:5601
    links:
     - elasticsearch